### ISSUE TITLE
strace-process-tree only shows last exec per pid

### ISSUE THREAD

**Issue by wader** [mgedmin/scripts#1]
Hi, thanks for the script! very useful

I noticed one thing that exec lines only show the last exec call for a pid so if a process exec multiple times only the last command and arguments will be shown in the tree. Might be a bit confusing some times.
I tried to do patch that kept a list of names per pid instead and it works but got messy printing it properly as a tree

**Comment by mgedmin** [comment]
Do you have a sample trace I could play with if I decide to tackle this?  (No promises!)

**Comment by wader** [comment]
That was fast :) Sure!
```sh
$ cat exec1
#!/bin/sh
echo exec1
exec ./exec2
$ cat exec2
#!/bin/sh
echo exec2
$ strace -f -e trace=process -s999999 -o strace.log ./exec1
exec1
exec2
$ cat strace.log
30217 execve("./exec1", ["./exec1"], [/* 25 vars */]) = 0
30217 arch_prctl(ARCH_SET_FS, 0x7efd409aa700) = 0
30217 execve("./exec2", ["./exec2"], [/* 25 vars */]) = 0
30217 arch_prctl(ARCH_SET_FS, 0x7f01362b5700) = 0
30217 exit_group(0)                     = ?
30217 +++ exited with 0 +++
$ python strace-process-tree strace.log
30217 ./exec2
```

**Comment by mgedmin** [comment]
> I tried to do patch that kept a list of names per pid instead and it works but got messy printing it properly as a tree

Also, that would not work if I wanted to show child processes executed before the parent does an execve() separately from child processes executed after the parent does an execve().

So I want the process-before and process-after to be different tree nodes, which is currently hard as tree nodes are identified by pid, which is the same for both.

I think I'll want to introduce a custom Process class to be used for dict indexing.

**Comment by mgedmin** [comment]
I wonder how many new bugs I've introduced by implementing this.  I hate not having a test suite.

(Having a test suite would imply moving this script into a separate Git repository and making it a full project, with a setup.py and PyPI releases.  Which is a good idea, but I need to muster the energy somehow.)

**Comment by wader** [comment]
Thanks! seems to work fine for a bigger strace log i have but don't think it has the situation your describing. And thanks again for the script!
